# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/vivado/PIC16CORE/PIC16CORE.cache/wt [current_project]
set_property parent.project_path /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/vivado/PIC16CORE/PIC16CORE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/vivado/PIC16CORE/PIC16CORE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/program.mem
read_verilog -library xil_defaultlib {
  /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/alu_op.v
  /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/alu.v
  /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/pic16core.v
  /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/pic16.v
}
read_vhdl -library xil_defaultlib /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/pic_dcm.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/pic16.xdc
set_property used_in_implementation false [get_files /lab/hicc/fajar/Documents/Programming-Practice/verilog/PIC16/PIC16F-Verilog-Core/pic16.xdc]


synth_design -top pic16 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef pic16.dcp

catch { report_utilization -file pic16_utilization_synth.rpt -pb pic16_utilization_synth.pb }
