#!/bin/bash

verilog clock24_test.v clock24.v counter12.v counter60.v counter24.v counter100.v led_drv.v seven_seg.v clock.v 

#make_vector.pl clock24_test.txt > clock24_test.vct

#wave viewer
#simvision
