// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x004003A8
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
        __gmon_start__();
        return;
    }
}

int printf(char* format)
{// addr = 0x004003E0
    goto __imp__printf;
}

__libc_start_main()
{// addr = 0x004003F0
    goto __imp____libc_start_main;
}

__gmon_start__()
{// addr = 0x00400400
    goto __imp____gmon_start__;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rdx                        // r56
)
{// addr = 0x00400410
    _unknown_ _t11;                        // _t11

    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __libc_start_main();
    asm("hlt");
    asm("o16 nop [rax+rax]");
    _push(_t11);
    if(6293783 -  &completed.6661 > 14 && 0 != 0) {
        _pop(__r8);
        goto __rax;
    }
    _pop(__r8);
}

deregister_tm_clones(
    _unknown_ __rax                        // r53
)
{// addr = 0x00400440
    _unknown_ _t7;                         // _t7

    _push(_t7);
    if(6293783 -  &completed.6661 <= 14 || 0 == 0) {
        _pop(__r8);
        return;
    } else {
        _pop(__r8);
        goto __rax;
    }
}

register_tm_clones(
    _unknown_ __rsi                        // r58
)
{// addr = 0x00400480
    _unknown_ _t12;                        // _t12

    _push(_t12);
    if(( &completed.6661 -  &completed.6661 >> 3) + ( &completed.6661 -  &completed.6661 >> 3 >> 63) == 0 || 0 == 0) {
        _pop(__r8);
        return;
    } else {
        _pop(__r8);
        goto __rax;
    }
}

__do_global_dtors_aux(
    long long* __rdi,                      // r57
    _unknown_ __rsi                        // r58
)
{// addr = 0x004004C0
    _unknown_ _t16;                        // _t16

    __rdi = __rdi;
    if(completed.6661 == 0) {
        _push(__r8);
        __r8 = __r9;
        deregister_tm_clones(__rax);
        _pop(__r8);
        completed.6661 = 1;
    }
    asm("repe ret");
    if( *__rdi != 0) {
        if(0 == 0) {
            goto L8;
        }
        _push(_t16);
        _t16 = __r9;
         *0();
        _pop(__r8);
L1:
        _push(_t16);
        if(( &completed.6661 -  &completed.6661 >> 3) + ( &completed.6661 -  &completed.6661 >> 3 >> 63) == 0 || 0 == 0) {
            _pop(__r8);
            return;
        } else {
            _pop(__r8);
            goto __rax;
        }
    }
L8:
    goto L1;
}

frame_dummy(
    long long* __rdi,                      // r57
    _unknown_ __rsi                        // r58
)
{// addr = 0x004004E0
    _unknown_ _t16;                        // _t16

    __rdi = __rdi;
    if( *__rdi != 0) {
        if(0 == 0) {
            goto L5;
        }
        _push(_t16);
        _t16 = __r9;
         *0();
        _pop(__r8);
    } else {
L5:
    }
    _push(_t16);
    if(( &completed.6661 -  &completed.6661 >> 3) + ( &completed.6661 -  &completed.6661 >> 3 >> 63) == 0 || 0 == 0) {
        _pop(__r8);
        return;
    } else {
        _pop(__r8);
        goto __rax;
    }
}

main(
    _unknown_ __rax,                       // r53
    _unknown_ __rdi                        // r57
)
{// addr = 0x00400506
    __rax = __rax;
    printf("Hello, World!");
}

__libc_csu_init(
    _unknown_ __rdx,                       // r56
    _unknown_ __rdi,                       // r57
    _unknown_ __rsi,                       // r58
    _unknown_ __r15                        // r66
)
{// addr = 0x00400520
    _unknown_ __rbx;                       // r54
    _unknown_ __r14;                       // r65
    _unknown_ __rbp;                       // r67
    _unknown_ __rsp;                       // r68
    _unknown_ _t3;                         // _t3
    _unknown_ _t7;                         // _t7
    signed long long _t8;                  // _t8
    _unknown_ _t13;                        // _t13
    signed long long _t16;                 // _t16
    _unknown_ _t17;                        // _t17
    _unknown_ _t22;                        // _t22

    __rdi = __rdi;
    _push(_t22);
    _push(_t3);
    _push(_t17);
    _push(_t13);
    _push(_t7);
    _t8 = 0;
    _t16 =  &__do_global_dtors_aux_fini_array_entry -  &__frame_dummy_init_array_entry >> 3;
    __r9 = __r9 - 8;
    _init();
    if( &__do_global_dtors_aux_fini_array_entry != 0) {
        do {
             *((intOrPtr*)( &__frame_dummy_init_array_entry + _t8 * 8))();
            _t8 = _t8 + 1;
        } while(_t8 != _t16);
    }
    __r9 = __r9 + 8;
    _pop(__rbx);
    _pop(__r8);
    _pop(__r14);
    _pop(__r15);
    _pop(__rbp);
}

__libc_csu_fini(
    intOrPtr* __rax                        // r53
)
{// addr = 0x00400590
    __rax = __rax;
    asm("repe ret");
     *__rax =  *__rax + __rax;
    __r9 = __r9 - 8;
    __r9 = __r9 + 8;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00400594
    __rax = __rax;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00400594
    __rax = __rax;
}

// Statistics:
//      61 Register nodes
//      21 Temporaries nodes
//       1 Casts
//      54 Statements
//       6 Labels
//       3 Gotos
//      13 Blocks
//     327 Nodes
//       4 Assembly nodes
//      27 Unknown Types


Total time: 0 seconds.
