// Generated by Rec Studio 4 - build Sep 23 2015

_init()
{// addr = 0x00400440
    __rax = __imp____gmon_start__;
    if(__rax != 0) {
        __gmon_start__();
        return;
    }
}

int strncmp(char* __s1, char* __s2, int __n)
{// addr = 0x00400470
    goto __imp__strncmp;
}

int printf(char* format)
{// addr = 0x00400480
    goto __imp__printf;
}

__libc_start_main()
{// addr = 0x00400490
    goto __imp____libc_start_main;
}

__gmon_start__()
{// addr = 0x004004A0
    goto __imp____gmon_start__;
}

__isoc99_scanf()
{// addr = 0x004004B0
    goto __imp____isoc99_scanf;
}

_start(
    _unknown_ __rax,                       // r53
    _unknown_ __rdx                        // r56
)
{// addr = 0x004004C0
    _unknown_ _t11;                        // _t11

    _pop(__rsi);
    __r9 = __r9 & -16;
    _push(__rax);
    _push(__r9);
    __libc_start_main();
    asm("hlt");
    asm("o16 nop [rax+rax]");
    _push(_t11);
    if(6294439 -  &completed.6661 > 14 && 0 != 0) {
        _pop(__r8);
        goto __rax;
    }
    _pop(__r8);
}

deregister_tm_clones(
    _unknown_ __rax                        // r53
)
{// addr = 0x004004F0
    _unknown_ _t7;                         // _t7

    _push(_t7);
    if(6294439 -  &completed.6661 <= 14 || 0 == 0) {
        _pop(__r8);
        return;
    } else {
        _pop(__r8);
        goto __rax;
    }
}

register_tm_clones(
    _unknown_ __rsi                        // r58
)
{// addr = 0x00400530
    _unknown_ _t12;                        // _t12

    _push(_t12);
    if(( &completed.6661 -  &completed.6661 >> 3) + ( &completed.6661 -  &completed.6661 >> 3 >> 63) == 0 || 0 == 0) {
        _pop(__r8);
        return;
    } else {
        _pop(__r8);
        goto __rax;
    }
}

__do_global_dtors_aux(
    long long* __rdi,                      // r57
    _unknown_ __rsi                        // r58
)
{// addr = 0x00400570
    _unknown_ _t16;                        // _t16

    __rdi = __rdi;
    if(completed.6661 == 0) {
        _push(__r8);
        __r8 = __r9;
        deregister_tm_clones(__rax);
        _pop(__r8);
        completed.6661 = 1;
    }
    asm("repe ret");
    if( *__rdi != 0) {
        if(0 == 0) {
            goto L8;
        }
        _push(_t16);
        _t16 = __r9;
         *0();
        _pop(__r8);
L1:
        _push(_t16);
        if(( &completed.6661 -  &completed.6661 >> 3) + ( &completed.6661 -  &completed.6661 >> 3 >> 63) == 0 || 0 == 0) {
            _pop(__r8);
            return;
        } else {
            _pop(__r8);
            goto __rax;
        }
    }
L8:
    goto L1;
}

frame_dummy(
    long long* __rdi,                      // r57
    _unknown_ __rsi                        // r58
)
{// addr = 0x00400590
    _unknown_ _t16;                        // _t16

    __rdi = __rdi;
    if( *__rdi != 0) {
        if(0 == 0) {
            goto L5;
        }
        _push(_t16);
        _t16 = __r9;
         *0();
        _pop(__r8);
    } else {
L5:
    }
    _push(_t16);
    if(( &completed.6661 -  &completed.6661 >> 3) + ( &completed.6661 -  &completed.6661 >> 3 >> 63) == 0 || 0 == 0) {
        _pop(__r8);
        return;
    } else {
        _pop(__r8);
        goto __rax;
    }
}

main(
    _unknown_ __rax,                       // r53
    int __rdx,                             // r56
    char* __rdi                            // r57
)
{// addr = 0x004005B6
    intOrPtr _v12;                         // _cfa_fffffff4
    long long _v32;                        // _cfa_ffffffe0
    long long _v40;                        // _cfa_ffffffd8
    long long _v48;                        // _cfa_ffffffd0
    long long _v56;                        // _cfa_ffffffc8
    long long _v64;                        // _cfa_ffffffc0
    long long _v72;                        // _cfa_ffffffb8
    long long _v80;                        // _cfa_ffffffb0
    long long _v88;                        // _cfa_ffffffa8
    long long _v96;                        // _cfa_ffffffa0
    long long _v104;                       // _cfa_ffffff98
    long long _v112;                       // _cfa_ffffff90
    long long _v120;                       // _cfa_ffffff88
    _unknown_ _v152;                       // _cfa_ffffff68
    char _v184;                            // _cfa_ffffff48
    signed long long _t59;                 // _t59
    char* _t61;                            // _t61

    _v72 = 4196260;
    _v64 = 4196265;
    _v56 = 4196270;
    _v48 = "emanresu";
    _v40 = "root";
    _v32 = "admin";
    _v120 = "Doe";
    _v112 = "Jane";
    _v104 = "Purnama";
    _v96 = "drowssap";
    _v88 = "toor";
    _v80 = "nimda";
    printf(__rdi);
    __isoc99_scanf();
    printf(__rdi);
    _t59 =  &_v184;
    __isoc99_scanf();
    _v12 = 0;
    while(_v12 <= 5) {
        _t61 =  *((intOrPtr*)(__r8 + _t59 * 8 - 64));
        _t59 =  &_v152;
        _t66 =  &_v152;
        if(strncmp( &_v152, _t61, __rdx) != 0) {
L4:
            if(_v12 == 5) {
                printf(_t66);
            }
            _v12 = _v12 + 1;
            continue;
        } else {
            _t59 =  &_v184;
            _t66 =  &_v184;
            if(strncmp( &_v184,  *(__r8 +  &_v152 * 8 - 112), __rdx) != 0) {
                goto L4;
            } else {
                printf( &_v184);
            }
        }
        break;
    }
}

__libc_csu_init(
    _unknown_ __rdx,                       // r56
    _unknown_ __rdi,                       // r57
    _unknown_ __rsi,                       // r58
    _unknown_ __r15                        // r66
)
{// addr = 0x00400720
    _unknown_ __rbx;                       // r54
    _unknown_ __r14;                       // r65
    _unknown_ __rbp;                       // r67
    _unknown_ __rsp;                       // r68
    _unknown_ _t3;                         // _t3
    _unknown_ _t7;                         // _t7
    signed long long _t8;                  // _t8
    _unknown_ _t13;                        // _t13
    signed long long _t16;                 // _t16
    _unknown_ _t17;                        // _t17
    _unknown_ _t22;                        // _t22

    __rdi = __rdi;
    _push(_t22);
    _push(_t3);
    _push(_t17);
    _push(_t13);
    _push(_t7);
    _t8 = 0;
    _t16 =  &__do_global_dtors_aux_fini_array_entry -  &__frame_dummy_init_array_entry >> 3;
    __r9 = __r9 - 8;
    _init();
    if( &__do_global_dtors_aux_fini_array_entry != 0) {
        do {
             *((intOrPtr*)( &__frame_dummy_init_array_entry + _t8 * 8))();
            _t8 = _t8 + 1;
        } while(_t8 != _t16);
    }
    __r9 = __r9 + 8;
    _pop(__rbx);
    _pop(__r8);
    _pop(__r14);
    _pop(__r15);
    _pop(__rbp);
}

__libc_csu_fini(
    intOrPtr* __rax                        // r53
)
{// addr = 0x00400790
    __rax = __rax;
    asm("repe ret");
     *__rax =  *__rax + __rax;
    __r9 = __r9 - 8;
    __r9 = __r9 + 8;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00400794
    __rax = __rax;
}

_fini(
    _unknown_ __rax                        // r53
)
{// addr = 0x00400794
    __rax = __rax;
}

// Statistics:
//      65 Register nodes
//      30 Temporaries nodes
//       2 Casts
//      73 Statements
//       8 Labels
//       4 Gotos
//      15 Blocks
//     464 Nodes
//       4 Assembly nodes
//      27 Unknown Types


Total time: 0 seconds.
